### PR TITLE
added DriveFire,HubDrive,KatDrive,Kolop GDrive Links

### PR DESCRIPTION
**Pull request by bipinkrish**

### CODE REVIEW

**Comment by TheCaduceus** [comment]
@bipinkrish Can you also create a PR in Link Bypasser Bot repository?

**Comment by bipinkrish** [comment]
> @bipinkrish Can you also create a PR in Link Bypasser Bot repository?

Sure

**Comment by TheCaduceus** [comment]
@bipinkrish Thanks a lot! ❤️

**Comment by bipinkrish** [comment]
> @bipinkrish Thanks a lot! heart

Done

**Comment by bipinkrish** [comment]
you can delete this fork https://github.com/TheCaduceus/Link-Bypasser-Bot-1

**Comment by TheCaduceus** [comment]
@bipinkrish Done! Thanks 👍

**Pull request merged**
